###
DELETE http://localhost:3000/api/posts/14
Content-Type: application/json
Authorization: Bearer 

###
POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
    "username": "john",
    "password": "johnpass"
}

###
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer 

{
    "user_id": 7,
    "note": "testi 16"
}

###
POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
    "username": "john",
    "password": "johnpass"
}

### Get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer 

###
DELETE  http://localhost:3000/api/users/1
Authorization: Bearer 

###
PUT http://localhost:3000/api/posts/10
Content-Type: application/json
Authorization: Bearer 

{
    "note": "changed note2"
}


###
GET http://localhost:3000/api/posts/5
Authorization: Bearer 

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "tom",
    "password": "tompass8",
    "email": "tom@example.com",
    "user_level": "regular"
}